version: '3'
services:
  # MySQL 마스터
  mysql-master:
    image: mysql:5.7
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: master_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - master-data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql.conf.d
      - ./db/master/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mysql-network

  # MySQL 슬레이브 1
  mysql-slave1:
    image: mysql:5.7
    container_name: mysql-slave1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: slave1_db
      MYSQL_USER: slave
      MYSQL_PASSWORD: password
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_MASTER_PORT: 3306
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: password
    volumes:
      - slave1-data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql.conf.d
      - ./db/slave1/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    networks:
      - mysql-network

  # MySQL 슬레이브 2
  mysql-slave2:
    image: mysql:5.7
    container_name: mysql-slave2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: slave2_db
      MYSQL_USER: slave
      MYSQL_PASSWORD: password
      MYSQL_MASTER_HOST: mysql-master
      MYSQL_MASTER_PORT: 3306
      MYSQL_MASTER_USER: root
      MYSQL_MASTER_PASSWORD: password
    volumes:
      - slave2-data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql.conf.d
      - ../db/slave2/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    networks:
      - mysql-network

networks:
  mysql-network:
    driver: bridge

volumes:
  master-data:
  slave1-data:
  slave2-data: