spring:
  jpa:
    show-sql: true

  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: '0000'

    rules:
      sharding:
        tables:
          users:
            actual-data-nodes: ds0.users_$->{0..1}
            table-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: user-inline
        binding-tables: users
        sharding-algorithms:
          user-inline:
            type: inline
            props:
              algorithm-expression: users_$->{user_id % 2}

        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true
